### ISSUE TITLE
building source successfully, error after "dotnet run"

### ISSUE THREAD

**Issue by abhelou** [aodpi/DentistBooking#1]
tried to build it on my ubuntu machine
after installation, i run "dotnet run"
i get this result
root@pedro-OMEN-by-HP-Laptop:~/DentistBooking/DentistBooking# dotnet run
Using launch settings from /home/pedro/DentistBooking/DentistBooking/Properties/launchSettings.json...

Unhandled Exception: System.NotSupportedException: The keyword 'integrated security' is not supported on this platform.
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass11_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at DentistBooking.Data.ApplicationDbContext.<Seed>d__2.MoveNext() in /home/pedro/DentistBooking/DentistBooking/Data/ApplicationDbContext.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

any missing part ? should i have sql on another iis server machine ? please advise

**Comment by aodpi** [comment]
Why do you need this project anyway ?

**Comment by abhelou** [comment]
I need it to help a dentist friend

**Comment by aodpi** [comment]
@abhelou This is just a dummy project anyway, you could change the database connection string to databases that work on ubuntu, postgresql for instance.
